name: Build and Push to ECR

on:
  workflow_dispatch:

jobs:
  build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Iniciar sesión en Amazon ECR
      run: |
        aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"

    - name: Build and push app1 image
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        cd app1
        docker build -t app1:latest -t $ECR_REGISTRY/app1:$IMAGE_TAG -t $ECR_REGISTRY/app1:latest .
        docker push $ECR_REGISTRY/app1:$IMAGE_TAG
        docker push $ECR_REGISTRY/app1:latest

    - name: Build and push app2 image
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        cd app2
        docker build -t app2:latest -t $ECR_REGISTRY/app2:$IMAGE_TAG -t $ECR_REGISTRY/app2:latest .
        docker push $ECR_REGISTRY/app2:$IMAGE_TAG
        docker push $ECR_REGISTRY/app2:latest
